version: "3.8"

services:
  mysql:
    image: mysql:lts
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123Root123
      MYSQL_DATABASE: finance_db
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis-container
    restart: unless-stopped
    command: redis-server
    environment:
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander-container
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  mysql-data:
  redis-data:
